# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20171029_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
