# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20171119_0252'),
        ('stock', '0012_auto_20171110_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('porcentaje_ganacia', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('stock_maximo', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('estante', models.CharField(max_length=10, null=True)),
                ('fila', models.CharField(max_length=10, null=True)),
                ('columna', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='columna',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estante',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fila',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_maximo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Sucursal'),
        ),
    ]
