# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20171119_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='porcentaje_ganacia',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto_ptr',
            field=models.OneToOneField(auto_created=True, default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.Producto'),
            preserve_default=False,
        ),
    ]
