# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20171119_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='producto_ptr',
        ),
        migrations.AddField(
            model_name='inventario',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='stock.Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:'),
        ),
    ]
