# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20171119_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='porcentaje_ganacia',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=999999, null=True),
        ),
    ]
