# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0017_auto_20171119_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Entrega pendiente'), (3, 'Entrega completa')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('descuento1', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('descuento2', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('descuento3', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'No recibido'), (2, 'Recibido')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.CodigoProducto')),
            ],
        ),
    ]
