# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0019_auto_20171216_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha:')),
                ('nro_comprobante', models.CharField(max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=256)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Comprobante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
