# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 04:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0020_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='gasto',
            name='comprobante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.Comprobante'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='created_date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
