# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20171217_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mes',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='mes',
            name='codigo',
            field=models.IntegerField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
