# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-02 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_auto_20171217_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
