# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-05 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_auto_20180902_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
