# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_auto_20180905_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
