# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='usuario',
        #    name='empresa',
        #    field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Empresa'),
        #    preserve_default=False,
        #    ),
        #migrations.AddField(
        #    model_name='usuario',
        #    name='sucursales',
        #    field=models.ManyToManyField(to='accounts.Sucursal'),
        #    ),
    ]
