# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171029_1415'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='usuario',
    #    name='empresa',
        #   ),
    ]
