# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usuario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sucursales',
            field=models.ManyToManyField(related_name='sucursales', to='accounts.Sucursal'),
        ),
    ]
