# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20171103_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='sucursales',
        ),
        migrations.AddField(
            model_name='perfil',
            name='sucursales',
            field=smart_selects.db_fields.GroupedForeignKey(default=1, group_field=b'empresa', on_delete=django.db.models.deletion.CASCADE, to='accounts.Sucursal'),
            preserve_default=False,
        ),
    ]
