# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:54
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171103_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='sucursales',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'empresa', chained_model_field=b'empresa', on_delete=django.db.models.deletion.CASCADE, to='accounts.Sucursal'),
        ),
    ]
