# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20171014_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=250)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('porcentaje_ganacia', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('stock_maximo', models.DecimalField(decimal_places=2, max_digits=999999, null=True)),
                ('estante', models.CharField(max_length=10, null=True)),
                ('fila', models.CharField(max_length=10, null=True)),
                ('columna', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:'),
        ),
        migrations.AddField(
            model_name='marca',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.UnidadMedida'),
        ),
    ]
