# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20171017_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_solcial',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
