# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_cliente_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='razon_solcial',
            new_name='razon_social',
        ),
    ]
