# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
