# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171029_1411'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='usuario',
        #    name='empresa',
        #    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Empresa'),
        #),
        #migrations.AlterField(
        #    model_name='usuario',
        #    name='sucursales',
        #    field=models.ManyToManyField(null=True, to='accounts.Sucursal'),
        #),
    ]
