# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_usuario_empresa'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='usuario',
    #    name='sucursales',
        #   ),
    ]
