# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20171102_2259'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('accounts', '0008_auto_20171103_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de creacion:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name=b'Fecha de actualizacion:')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Empresa')),
                ('sucursales', models.ManyToManyField(to='accounts.Sucursal')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sucursales',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
