# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171103_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sucursales',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='empresa', chained_model_field='empresa', to='accounts.Sucursal'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion:'),
        ),
    ]
