# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20171119_0528'),
        ('accounts', '0015_auto_20171119_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='box_daily',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.Caja'),
            preserve_default=False,
        ),
    ]
