# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_perfil_box_daily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='box_daily',
        ),
    ]
